/**
 * UUIDv7 generation (RFC 9562): time-ordered, index-friendly ids everywhere (AGENTS.md).
 *
 * Layout (128 bits):
 *   - unix_ts_ms : 48 bits, big-endian (bytes 0–5)
 *   - ver        : 4 bits  = 0b0111
 *   - rand_a     : 12 bits — process-local monotonic counter (bytes 6–7)
 *   - var        : 2 bits  = 0b10
 *   - rand_b     : 62 bits — random (bytes 8–15)
 *
 * The 12-bit counter makes ids generated by one process strictly monotonic (lexicographic order ==
 * generation order), which the test suite asserts. Uses only WebCrypto (`globalThis.crypto`), so the
 * code is Node LTS- and Bun-compatible with no runtime-specific imports.
 */

/** The nil uuid — used to coalesce NULL scope columns in dedupe keys/indexes. */
export const NIL_UUID = '00000000-0000-0000-0000-000000000000';

let lastMs = 0;
let lastSeq = 0;

export function uuidv7(nowMs?: number): string {
  let ms = nowMs ?? Date.now();
  if (ms < lastMs) ms = lastMs; // never move time backwards (monotonicity over wall-clock truth)

  let seq: number;
  if (ms === lastMs) {
    seq = (lastSeq + 1) & 0xfff;
    if (seq === 0) ms += 1; // counter overflow within the same millisecond → advance one tick
  } else {
    seq = 0;
  }
  lastMs = ms;
  lastSeq = seq;

  const bytes = new Uint8Array(16);
  const view = new DataView(bytes.buffer);
  view.setUint16(0, Math.floor(ms / 2 ** 32));
  view.setUint32(2, ms >>> 0);
  view.setUint8(6, 0x70 | ((seq >> 8) & 0x0f)); // version 7 + high 4 bits of rand_a
  view.setUint8(7, seq & 0xff); // low 8 bits of rand_a
  globalThis.crypto.getRandomValues(bytes.subarray(8));
  bytes[8] = (bytes[8]! & 0x3f) | 0x80; // RFC 9562 variant = 0b10

  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
  return [
    hex.slice(0, 8),
    hex.slice(8, 12),
    hex.slice(12, 16),
    hex.slice(16, 20),
    hex.slice(20, 32),
  ].join('-');
}

/** RFC 9562 uuid (any version) shape check — used at validation boundaries. */
export function isUuid(value: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value);
}
