/**
 * The AGENTS.md bootstrap (deliverable 2) — ADR-0010 §7: interop, not competition.
 *
 * Codex discovers `AGENTS.md` global→project root→cwd, concatenates the files, and caps the
 * combined size at `project_doc_max_bytes` (32 KiB default). onememory therefore writes a COMPACT
 * GENERATED POINTER (~0.7 KiB): who owns project memory, which tools to use, and an explicit
 * "do not maintain a duplicate knowledge base here". It is never a memory dump, never
 * hand-maintained state — the durable knowledge lives in onememory and is fetched with
 * `memory_project_context` / `memory_search`.
 *
 * Patching is fenced and idempotent: the block sits between HTML-comment markers, re-running
 * replaces exactly the marked region, and everything around it is preserved byte-for-byte.
 */

export const AGENTS_BLOCK_BEGIN_PREFIX = '<!-- onememory:begin project=';
export const AGENTS_BLOCK_END_MARKER = '<!-- onememory:end -->';

export interface AgentsBlockOptions {
  /** UUIDv7 project id — embedded in the begin marker so a stale block is detectable. */
  projectId: string;
}

/** Render the generated pointer block (with its markers). */
export function renderOnememoryAgentsBlock(options: AgentsBlockOptions): string {
  const lines = [
    `<!-- onememory:begin project=${options.projectId} (generated by onemem init; safe to re-run) -->`,
    '## Project memory',
    '',
    'Long-term memory for this project (decisions, failures, conventions, procedures) lives in',
    'onememory, not in this file. Read and write it with the `onememory` MCP tools:',
    '',
    '- `memory_search(query)` returns a compact id-index with token estimates; follow with',
    '  `memory_get(id)` for the full record.',
    '- `memory_store(content)` persists a durable fact and reports `new`/`merged`/`superseded`.',
    '- `memory_project_context` is the packed session summary, injected automatically at session',
    '  start when the onememory daemon (`onemem serve`) is running.',
    '- "Remember that ..." requests are captured automatically by the onememory hooks.',
    '',
    'Keep this file for human-authored guidance only — do not maintain a duplicate knowledge',
    'base here, and do not hand-edit the onememory block (re-run `onemem init` instead).',
    AGENTS_BLOCK_END_MARKER,
  ];
  return lines.join('\n');
}

/**
 * Idempotently patch an AGENTS.md document with the generated block.
 *
 * - an existing onememory block (any `<!-- onememory:begin … -->` … `<!-- onememory:end -->`
 *   region) is replaced in place, wherever it sits in the file;
 * - otherwise the block is appended at the end with clean blank-line separation;
 * - everything else is preserved byte-for-byte.
 */
export function patchAgentsMd(existing: string, block: string): string {
  const beginIndex = existing.indexOf(AGENTS_BLOCK_BEGIN_PREFIX);
  if (beginIndex !== -1) {
    const endIndex = existing.indexOf(AGENTS_BLOCK_END_MARKER, beginIndex);
    if (endIndex !== -1) {
      const before = existing.slice(0, beginIndex);
      const after = existing.slice(endIndex + AGENTS_BLOCK_END_MARKER.length);
      const joined = `${before}${block}${after.startsWith('\n') || after.length === 0 ? after : `\n${after}`}`;
      return joined;
    }
    // Corrupt markers (begin without end): leave the file alone rather than splice blindly —
    // the caller reports it as a warning.
    return existing;
  }

  const normalizedBlock = `${block.trim()}\n`;
  if (existing.trim().length === 0) return normalizedBlock;
  const separator = existing.endsWith('\n\n') || existing.endsWith('\n') ? '\n' : '\n\n';
  return `${existing}${separator}${normalizedBlock}`;
}

/** `true` when the document contains a complete onememory block for this project id. */
export function hasOnememoryAgentsBlock(content: string, projectId: string): boolean {
  const beginIndex = content.indexOf(`${AGENTS_BLOCK_BEGIN_PREFIX}${projectId}`);
  if (beginIndex === -1) return false;
  return content.includes(AGENTS_BLOCK_END_MARKER, beginIndex);
}
