/**
 * The Codex `config.toml` MCP scaffold (deliverable 1).
 *
 * Every field emitted is verified against the Codex MCP documentation
 * (https://developers.openai.com/codex/mcp, read 2026-10-03): stdio servers take `command`
 * (required), `args`, `env` (a name→value table), `env_vars` (names forwarded from Codex's own
 * environment), `cwd`, `startup_timeout_sec`; per-server knobs `enabled`/`required`/
 * `enabled_tools`/`default_tools_approval_mode`; and the per-tool
 * `tools.<tool>.output_token_limit` budget (+20% serialization allowance).
 *
 * Patching is text-splice idempotent, never a parse/stringify round-trip: a user's config.toml
 * carries comments and unrelated tables, and rewriting it would clobber them (the same
 * comment-preserving rule `packages/config` applies to onememory.yaml). The block is fenced with
 * marker comments; a pre-existing unmarked `[mcp_servers.onememory]` section (hand-added before
 * onememory arrived) is replaced in place so the file can never end up with two onememory tables.
 */

export const CODEX_TOML_BEGIN_MARKER = '# --- onememory:begin (generated by `onemem init`; safe to re-run — edit outside the markers) ---';
export const CODEX_TOML_END_MARKER = '# --- onememory:end ---';

export const ONEMEMORY_MCP_SERVER_NAME = 'onememory';

export interface CodexMcpScaffoldOptions {
  /** UUIDv7 project id (`scope.project_id` for the server). */
  projectId: string;
  /** stdio command that starts `onemem-mcp` (default `onemem-mcp`, the published bin name). */
  mcpCommand?: string;
  /** Arguments for the command (rarely needed; the bin is env-configured). */
  args?: string[];
  /** Tool exposure profile (mission-5: `default8` | `full11`). */
  profile?: 'default8' | 'full11';
  /** Stored agent_id / audited actor for MCP writes (default `codex`). */
  agentId?: string;
  /**
   * Embedded data dir. Absolute paths are emitted verbatim (user-scope installs); omit to let
   * `ONEMEMORY_DATA_DIR` arrive via `env_vars` forwarding (default `.onememory` under the
   * launch dir).
   */
  dataDir?: string;
  /** Working directory for the stdio server process (user-scope installs pass an absolute path). */
  cwd?: string;
  /** Startup ceiling (default 20s — cold PGlite boot can exceed Codex's 10s default). */
  startupTimeoutSec?: number;
}

/** Render the marked `[mcp_servers.onememory]` block. */
export function renderCodexMcpServerToml(options: CodexMcpScaffoldOptions): string {
  const command = options.mcpCommand ?? 'onemem-mcp';
  const profile = options.profile ?? 'default8';
  const agentId = options.agentId ?? 'codex';
  const startupTimeoutSec = options.startupTimeoutSec ?? 20;

  const lines: string[] = [
    CODEX_TOML_BEGIN_MARKER,
    '# onememory — persistent project memory for Codex (stdio MCP server).',
    '# Env forwarded from YOUR shell when set (server mode wins over embedded):',
    '#   ONEMEMORY_PG_URL   credential-free postgres:// URL for server-mode storage',
    '#   ONEMEMORY_DATA_DIR embedded PGlite data dir (default ".onememory")',
    `[mcp_servers.${ONEMEMORY_MCP_SERVER_NAME}]`,
    `command = ${tomlString(command)}`,
  ];
  if (options.args !== undefined && options.args.length > 0) {
    lines.push(`args = [${options.args.map((arg) => tomlString(arg)).join(', ')}]`);
  }
  if (options.cwd !== undefined) {
    lines.push(`cwd = ${tomlString(options.cwd)}`);
  }
  lines.push(`startup_timeout_sec = ${startupTimeoutSec}`);
  lines.push('env_vars = ["ONEMEMORY_PG_URL", "ONEMEMORY_DATA_DIR"]');
  lines.push('');
  lines.push(`[mcp_servers.${ONEMEMORY_MCP_SERVER_NAME}.env]`);
  lines.push(`ONEMEMORY_PROJECT_ID = ${tomlString(options.projectId)}`);
  lines.push(`ONEMEMORY_MCP_PROFILE = ${tomlString(profile)}`);
  lines.push(`ONEMEMORY_MCP_AGENT_ID = ${tomlString(agentId)}`);
  if (options.dataDir !== undefined) {
    lines.push(`ONEMEMORY_DATA_DIR = ${tomlString(options.dataDir)}`);
  }
  lines.push('');
  lines.push('# Codex enforces a per-tool output budget: tools.<tool>.output_token_limit (a positive');
  lines.push('# token count before the standard 20% serialization allowance). onememory results are');
  lines.push('# already budgeted — memory_search honors max_tokens and returns a token_estimate per');
  lines.push('# row — so leave the default unless you want a tighter cap, e.g.:');
  lines.push('#');
  lines.push('# [mcp_servers.onememory.tools.memory_search]');
  lines.push('# output_token_limit = 1200');
  lines.push(CODEX_TOML_END_MARKER);
  return lines.join('\n');
}

/**
 * Idempotently patch a `config.toml` with the onememory server block.
 *
 * - marked block present → replaced in place;
 * - unmarked `[mcp_servers.onememory]` table present → that section is replaced in place;
 * - otherwise → appended with a blank-line separator.
 *
 * User content outside the replaced region is preserved byte-for-byte.
 */
export function patchCodexConfigToml(existing: string, block: string): string {
  const normalizedBlock = `${block.trim()}\n`;
  const beginIndex = existing.indexOf(CODEX_TOML_BEGIN_MARKER);
  if (beginIndex !== -1) {
    const endIndex = existing.indexOf(CODEX_TOML_END_MARKER, beginIndex);
    if (endIndex !== -1) {
      // Everything after the end marker; the newline terminating the marker line itself belongs
      // to the block (it is re-emitted by `normalizedBlock`), so consume it here — that is what
      // makes re-patching byte-idempotent instead of accumulating blank lines.
      let after = existing.slice(endIndex + CODEX_TOML_END_MARKER.length);
      if (after.startsWith('\r\n')) after = after.slice(2);
      else if (after.startsWith('\n')) after = after.slice(1);
      const trailing =
        after.length === 0 ? '' : after.startsWith('\n') || after.startsWith('\r\n') ? after : `\n${after}`;
      return `${existing.slice(0, beginIndex)}${normalizedBlock}${trailing}`;
    }
    // A begin marker without an end marker is corrupt; fall through and append a fresh block.
  }

  const sectionRange = existingOnememorySectionRange(existing);
  if (sectionRange !== null) {
    const before = existing.slice(0, sectionRange.start);
    const after = existing.slice(sectionRange.end);
    const separatorBefore = before.endsWith('\n\n') || before.length === 0 ? '' : before.endsWith('\n') ? '\n' : '\n\n';
    return `${before}${separatorBefore}${normalizedBlock}${after.startsWith('\n') || after.length === 0 ? after : `\n${after}`}`;
  }

  if (existing.trim().length === 0) return normalizedBlock;
  const separator = existing.endsWith('\n\n') ? '' : existing.endsWith('\n') ? '\n' : '\n\n';
  return `${existing}${separator}${normalizedBlock}`;
}

/** Locate a pre-existing unmarked `[mcp_servers.onememory]` table (start/end line offsets). */
function existingOnememorySectionRange(existing: string): { start: number; end: number } | null {
  const lines = existing.split('\n');
  const header = lines.findIndex((line) => /^\[mcp_servers\.onememory\]\s*$/.test(line));
  if (header === -1) return null;

  let end = lines.length; // exclusive
  for (let index = header + 1; index < lines.length; index += 1) {
    if (/^\s*\[/.test(lines[index]!)) {
      end = index;
      break;
    }
  }
  // Trim trailing blank lines out of the replaced region so the file doesn't accumulate gaps.
  while (end > header + 1 && lines[end - 1]!.trim().length === 0) end -= 1;
  if (end === header + 1) end = header + 1;

  const startOffset = lines.slice(0, header).reduce((sum, line) => sum + line.length + 1, 0);
  const endOffset = lines.slice(0, end).reduce((sum, line) => sum + line.length + 1, 0);
  return { start: startOffset, end: Math.min(endOffset, existing.length) };
}

/** TOML basic-string escaping (control characters, quotes, backslashes). */
export function tomlString(value: string): string {
  let escaped = '"';
  for (const char of value) {
    const code = char.codePointAt(0)!;
    if (char === '"') escaped += '\\"';
    else if (char === '\\') escaped += '\\\\';
    else if (code === 0x0a) escaped += '\\n';
    else if (code === 0x09) escaped += '\\t';
    else if (code === 0x0d) escaped += '\\r';
    else if (code < 0x20 || code === 0x7f) escaped += `\\u${code.toString(16).padStart(4, '0')}`;
    else escaped += char;
  }
  return `${escaped}"`;
}
