/**
 * The Codex hooks scaffold — the live capture channel (deliverable 3).
 *
 * The emitted shape is the verified hooks.json contract (https://developers.openai.com/codex/hooks,
 * 2026-10-03): `{ "description", "hooks": { <Event>: [ { "matcher"?, "hooks": [ handler ] } ] } }`
 * with `command` handlers `{ "type": "command", "command", "timeout"?, "async"?, "statusMessage"? }`.
 *
 * Every registered handler is the same `onemem-codex-capture` bin reading the hook JSON from
 * stdin and dispatching on `hook_event_name`. Capture handlers run `async` (they never block the
 * agent; ≤8 concurrent background hooks per session). The SessionStart handler runs synchronously
 * because context injection must land in the first model request; the bin bounds its own delivery
 * work to 2.5s internally, well under the handler's 10s ceiling. SessionEnd is always synchronous
 * in Codex and capped at 3s — the bin's internal delivery timeout (2.5s) fits inside it.
 *
 * Codex requires trust review (`/hooks`) before non-managed hooks run — the scaffold cannot and
 * must not bypass that; the README makes it the first setup step.
 */

export interface CodexHooksScaffoldOptions {
  /** The capture command (default `onemem-codex-capture`, the published bin name). */
  captureCommand?: string;
  /** Install the SessionStart context-injection handler (default true). */
  includeSessionStart?: boolean;
  /** Install the per-event capture handlers (default true). */
  includeCapture?: boolean;
  /** Hook timeout ceiling in seconds for the async capture handlers (default 30). */
  captureTimeoutSec?: number;
}

interface HookHandler {
  type: 'command';
  command: string;
  timeout?: number;
  async?: boolean;
  statusMessage?: string;
}

interface HookMatcherGroup {
  matcher?: string;
  hooks: HookHandler[];
}

export interface CodexHooksFile {
  description?: string;
  hooks: Record<string, HookMatcherGroup[]>;
}

/** Build the generated hooks.json object. */
export function buildCodexHooksFile(options: CodexHooksScaffoldOptions = {}): CodexHooksFile {
  const command = options.captureCommand ?? 'onemem-codex-capture';
  const includeSessionStart = options.includeSessionStart ?? true;
  const includeCapture = options.includeCapture ?? true;
  const captureTimeoutSec = options.captureTimeoutSec ?? 30;

  const captureHandler: HookHandler = { type: 'command', command, async: true, timeout: captureTimeoutSec };
  const hooks: Record<string, HookMatcherGroup[]> = {};

  if (includeSessionStart) {
    hooks['SessionStart'] = [
      {
        hooks: [
          {
            type: 'command',
            command,
            timeout: 10,
            statusMessage: 'Loading onememory project context',
          },
        ],
      },
    ];
  }
  if (includeCapture) {
    hooks['UserPromptSubmit'] = [{ hooks: [captureHandler] }];
    hooks['PostToolUse'] = [
      { matcher: '^Bash$', hooks: [captureHandler] },
      { matcher: '^(apply_patch|Edit|Write)$', hooks: [captureHandler] },
    ];
    hooks['Stop'] = [{ hooks: [captureHandler] }];
    hooks['SessionEnd'] = [{ hooks: [{ type: 'command', command, timeout: 3 }] }];
  }
  return {
    description: 'onememory capture hooks (generated by onemem init)',
    hooks,
  };
}

/** Serialize the hooks.json document (stable key order, 2-space indent, trailing newline). */
export function renderCodexHooksJson(options: CodexHooksScaffoldOptions = {}): string {
  return `${JSON.stringify(buildCodexHooksFile(options), null, 2)}\n`;
}

export interface HooksPatchResult {
  content: string;
  action: 'created' | 'patched' | 'unchanged';
}

/**
 * Idempotently merge the generated hooks into an existing hooks.json.
 *
 * Entries whose handlers reference the onememory capture command are REPLACED (re-running init
 * must not register duplicate handlers — Codex runs every matching hook); everything else in the
 * file (other tools' hooks, user metadata) is preserved. An unparseable existing file is an
 * error, never clobbered.
 */
export function patchCodexHooksJson(
  existing: string,
  options: CodexHooksScaffoldOptions = {},
): HooksPatchResult | { error: string } {
  const generated = buildCodexHooksFile(options);
  const token = options.captureCommand ?? 'onemem-codex-capture';

  if (existing.trim().length === 0) {
    return { content: renderCodexHooksJson(options), action: 'created' };
  }

  let parsed: CodexHooksFile;
  try {
    parsed = JSON.parse(existing) as CodexHooksFile;
  } catch (error) {
    return {
      error: `hooks.json is not valid JSON and was left untouched: ${
        error instanceof Error ? error.message : String(error)
      }`,
    };
  }
  if (typeof parsed !== 'object' || parsed === null || typeof parsed.hooks !== 'object' || parsed.hooks === null) {
    return { error: 'hooks.json has no "hooks" object and was left untouched' };
  }

  const isOurs = (group: HookMatcherGroup): boolean =>
    Array.isArray(group.hooks) &&
    group.hooks.some((handler) => typeof handler.command === 'string' && handler.command.includes(token));

  const merged: CodexHooksFile = {
    ...parsed,
    hooks: { ...parsed.hooks },
  };
  for (const [event, generatedGroups] of Object.entries(generated.hooks)) {
    const existingGroups = Array.isArray(merged.hooks[event]) ? (merged.hooks[event] as HookMatcherGroup[]) : [];
    const preserved = existingGroups.filter((group) => !isOurs(group));
    merged.hooks[event] = [...preserved, ...generatedGroups];
  }

  const content = `${JSON.stringify(merged, null, 2)}\n`;
  return { content, action: content === existing ? 'unchanged' : 'patched' };
}
