/**
 * Transcript reader + delta selection tests. The fixture lines use the long-stable
 * `type: "user" | "assistant"` + `message.content` shapes; the sessions reference documents the
 * format as internal and version-dependent, so every unrecognized line must come back as a
 * COUNTED drop — the parser must never throw, never coerce, and never persist content.
 */

import { describe, expect, test } from 'bun:test';

import { parseTranscript, selectTranscriptDelta, MAX_EVENTS_PER_DELIVERY, type TranscriptEntry } from './transcript';

const userText = (uuid: string, text: string, timestamp = '2026-10-03T09:00:00.000Z'): string =>
  JSON.stringify({
    parentUuid: 'p',
    uuid,
    type: 'user',
    message: { role: 'user', content: text },
    timestamp,
    sessionId: 'abc123',
    cwd: '/p',
    version: '2.1.0',
    gitBranch: 'main',
  });

const assistantText = (uuid: string, text: string, timestamp = '2026-10-03T09:00:01.000Z'): string =>
  JSON.stringify({
    parentUuid: 'p',
    uuid,
    type: 'assistant',
    message: { id: 'msg_1', role: 'assistant', content: [{ type: 'text', text }] },
    timestamp,
  });

describe('parseTranscript', () => {
  test('parses string-content user lines and block-content assistant lines with their uuids', () => {
    const parsed = parseTranscript(`${userText('u1', 'hello')}\n${assistantText('u2', 'Running now.')}\n`);
    expect(parsed.drops).toEqual([]);
    expect(parsed.entries).toEqual([
      { kind: 'text', role: 'user', text: 'hello', uuid: 'u1', timestamp: '2026-10-03T09:00:00.000Z' },
      { kind: 'text', role: 'assistant', text: 'Running now.', uuid: 'u2', timestamp: '2026-10-03T09:00:01.000Z' },
    ]);
  });

  test('assistant plain-string content parses too (older transcript shapes)', () => {
    const line = JSON.stringify({ uuid: 'u3', type: 'assistant', message: { role: 'assistant', content: 'plain' }, timestamp: '2026-10-03T09:00:02.000Z' });
    const parsed = parseTranscript(line);
    expect(parsed.entries).toEqual([{ kind: 'text', role: 'assistant', text: 'plain', uuid: 'u3', timestamp: '2026-10-03T09:00:02.000Z' }]);
  });

  test('tool-result user entries are skipped with a counted reason (they are not utterances)', () => {
    const line = JSON.stringify({
      uuid: 'u4',
      type: 'user',
      message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: 't1', content: [{ type: 'text', text: '87 pass' }] }] },
      timestamp: '2026-10-03T09:00:03.000Z',
    });
    const parsed = parseTranscript(line);
    expect(parsed.entries.map((entry) => entry.kind)).toEqual(['skipped']);
    expect(parsed.entries[0]).toMatchObject({ reason: 'transcript_tool_result_entry', uuid: 'u4' });
  });

  test('machine-generated wrappers are skipped (system reminders, command telemetry)', () => {
    const parsed = parseTranscript(
      [
        userText('u5', '<system-reminder>Your todo list is empty</system-reminder>'),
        userText('u6', '<command-name>/init</command-name>'),
        userText('u7', '<local-command-stdout>done</local-command-stdout>'),
        userText('u8', 'Caveat: The messages below were generated by the user'),
        userText('u9', 'Real user speech'),
      ].join('\n'),
    );
    const textEntries = parsed.entries.filter((entry) => entry.kind === 'text');
    expect(textEntries.map((entry) => (entry as { text: string }).text)).toEqual(['Real user speech']);
    const skipped = parsed.entries.filter((entry) => entry.kind === 'skipped');
    expect(skipped).toHaveLength(4);
    expect(new Set(skipped.map((entry) => (entry as { reason: string }).reason))).toEqual(
      new Set(['transcript_machine_generated']),
    );
  });

  test('summary lines and unknown types are skipped with their type counted', () => {
    const parsed = parseTranscript(
      [
        JSON.stringify({ type: 'summary', summary: 's', leafUuid: 'u1' }),
        JSON.stringify({ type: 'system', content: 'x' }),
        JSON.stringify({ type: 'progress', x: 1 }),
      ].join('\n'),
    );
    expect(parsed.entries.every((entry) => entry.kind === 'skipped')).toBeTrue();
    expect(parsed.entries.map((entry) => (entry as { reason: string }).reason)).toEqual([
      'transcript_entry_type:summary',
      'transcript_entry_type:system',
      'transcript_entry_type:progress',
    ]);
  });

  test('garbage lines are counted, never thrown', () => {
    const parsed = parseTranscript(['not json at all', '{"broken"', userText('u1', 'ok')].join('\n'));
    expect(parsed.drops).toEqual([{ reason: 'transcript_unparseable_line', count: 2 }]);
    expect(parsed.entries.map((entry) => (entry as { text: string }).text)).toEqual(['ok']);
  });

  test('entries with no text blocks are skipped', () => {
    const line = JSON.stringify({
      uuid: 'u2',
      type: 'assistant',
      message: { role: 'assistant', content: [{ type: 'tool_use', id: 't1', name: 'Bash', input: {} }] },
      timestamp: '2026-10-03T09:00:04.000Z',
    });
    const parsed = parseTranscript(line);
    expect(parsed.entries[0]).toMatchObject({ kind: 'skipped', reason: 'transcript_no_text_blocks' });
  });
});

describe('selectTranscriptDelta', () => {
  const entries: TranscriptEntry[] = [
    { kind: 'text', role: 'user', text: 'one', uuid: 'u1' },
    { kind: 'text', role: 'user', text: 'two', uuid: 'u2' },
    { kind: 'skipped', reason: 'transcript_tool_result_entry', uuid: 'u3' },
    { kind: 'text', role: 'user', text: 'three', uuid: 'u4' },
  ];

  test('delivers only entries after the cursor', () => {
    const delta = selectTranscriptDelta(entries, 'u2');
    expect(delta.deliver.map((entry) => entry.text)).toEqual(['three']);
    expect(delta.nextCursor).toBe('u4');
    expect(delta.rescanned).toBeFalse();
    expect(delta.drops).toEqual([{ reason: 'transcript_tool_result_entry', count: 1 }]);
  });

  test('a lost cursor rescans the whole file (over-delivery is deduped by the daemon)', () => {
    const delta = selectTranscriptDelta(entries, 'gone-uuid');
    expect(delta.rescanned).toBeTrue();
    expect(delta.deliver.map((entry) => entry.text)).toEqual(['one', 'two', 'three']);
    expect(delta.nextCursor).toBe('u4');
  });

  test('a null cursor (first run) selects everything', () => {
    const delta = selectTranscriptDelta(entries, null);
    expect(delta.rescanned).toBeFalse();
    expect(delta.deliver.map((entry) => entry.text)).toEqual(['one', 'two', 'three']);
  });

  test('nothing new keeps the cursor unchanged', () => {
    const delta = selectTranscriptDelta(entries, 'u4');
    expect(delta.deliver).toEqual([]);
    expect(delta.nextCursor).toBe('u4');
  });

  test('skipped-only progress advances the cursor so the lines are never rescanned', () => {
    const tail: TranscriptEntry[] = [...entries, { kind: 'skipped', reason: 'transcript_machine_generated', uuid: 'u5' }];
    const delta = selectTranscriptDelta(tail, 'u4');
    expect(delta.deliver).toEqual([]);
    expect(delta.nextCursor).toBe('u5');
  });

  test('the delivery cap delivers the OLDEST events first; the remainder arrives next Stop', () => {
    const many: TranscriptEntry[] = Array.from({ length: MAX_EVENTS_PER_DELIVERY + 40 }, (_, index) => ({
      kind: 'text' as const,
      role: 'user' as const,
      text: `message-${index}`,
      uuid: `u-${index}`,
    }));
    const delta = selectTranscriptDelta(many, null);
    expect(delta.deliver).toHaveLength(MAX_EVENTS_PER_DELIVERY);
    // Oldest-first: under-delivery loses memories, so the backlog starts at the head.
    expect(delta.deliver[0]!.text).toBe('message-0');
    expect(delta.deliver[MAX_EVENTS_PER_DELIVERY - 1]!.text).toBe(`message-${MAX_EVENTS_PER_DELIVERY - 1}`);
    // The cursor advanced only past what was delivered — nothing is orphaned.
    expect(delta.nextCursor).toBe(`u-${MAX_EVENTS_PER_DELIVERY - 1}`);
    const next = selectTranscriptDelta(many, delta.nextCursor);
    expect(next.deliver.map((entry) => entry.text)).toEqual(
      Array.from({ length: 40 }, (_, index) => `message-${MAX_EVENTS_PER_DELIVERY + index}`),
    );
  });
});
