/**
 * The default configuration and the annotated template `onemem init` writes.
 *
 * Every default is 100% local (AGENTS.md rule 4): embedded PGlite storage, no LLM providers, no
 * embedder. In that state retrieval runs on the lexical + graph channels and the extractor runs on
 * heuristics — the product's default state, and the state `onemem doctor` must pass in.
 */

import {
  DEFAULT_CONSOLIDATE_INTERVAL_MS,
  DEFAULT_DAEMON_PORT,
  DEFAULT_RETENTION_DAYS,
  parseConfig,
  type OnememoryConfig,
} from './schema';

/** Directory that holds the config file, project state, data dir and daemon lock. */
export const CONFIG_DIR_NAME = '.onememory';
/** The config file name inside {@link CONFIG_DIR_NAME}. */
export const CONFIG_FILE_NAME = 'onememory.yaml';
/** Accepted alternative spelling. */
export const CONFIG_FILE_NAME_ALT = 'onememory.yml';
/** Environment variable naming an explicit config file. */
export const CONFIG_PATH_ENV = 'ONEMEMORY_CONFIG';

/** The fully-defaulted config object (no file involved). */
export function defaultConfigObject(): OnememoryConfig {
  return parseConfig({});
}

/**
 * The annotated config template. Comments document every section and every optional switch; the
 * active lines are exactly the local-first defaults, so an untouched file behaves like the
 * built-in defaults (verified by a round-trip test).
 */
export function renderDefaultConfigYaml(): string {
  return `# onememory configuration — local-first defaults.
# Generated by 'onemem init'. Everything here works offline: no account, no telemetry,
# no external AI calls. Optional sections are documented as comments.

version: 1

# Project identity. 'onemem init' records the registered project in .onememory/project.json
# (machine-managed); these fields are informational overrides.
project:
  name: $PROJECT_NAME$
  # root_path: .
  # git_remote: git@github.com:you/your-repo.git

storage:
  mode: embedded            # embedded (PGlite, exactly one owner process) | server (Postgres + pgvector)
  data_dir: .onememory/data
  vector_backend: auto      # auto | pgvector | float8  (auto probes the extension, falls back loudly)
  # pg_url: ONEMEMORY_PG_URL  # server mode only — an environment variable NAME, never a password inline

# Semantic recall is optional. Without an embedder, retrieval uses the lexical + graph channels
# and says so in 'onemem doctor' and in every search response's warnings.
# embeddings:
#   provider: ollama                     # ollama | openai-compatible | local-transformers
#   model: nomic-embed-text
#   dim: 768                             # omit to discover the dimension via probe()
#   base_url: http://127.0.0.1:11434     # loopback only while llm.profile is local

# The model router (ADR-0006). 'routes' is strict: an unknown operation key is a typo and fails.
# An operation with no route degrades honestly (heuristics / lexical), never silently to a cloud API.
llm:
  profile: local            # local | hybrid | server
  providers: []
  routes: {}
  # providers:
  #   - id: ollama
  #     kind: ollama                        # openai | anthropic | google | openai-compatible | ollama
  #     base_url: http://127.0.0.1:11434/v1
  #   - id: openai
  #     kind: openai
  #     api_key_env: ONEMEMORY_OPENAI_API_KEY   # environment variable NAME, never the key itself
  # routes:
  #   extract:      { provider: ollama, model: qwen3:8b }
  #   classify:     { provider: ollama, model: qwen3:8b }
  #   consolidate:  { provider: ollama, model: qwen3:8b }
  #   conflict:     { provider: ollama, model: qwen3:8b }
  #   summarize:    { provider: ollama, model: qwen3:8b }
  #   embedding:    { provider: ollama, model: nomic-embed-text }
  # defaults: { temperature: 0.2, max_retries: 2, max_output_tokens: 2048, timeout_ms: 60000 }

daemon:
  host: 127.0.0.1           # loopback only unless 'onemem serve --listen-public' is passed
  port: ${DEFAULT_DAEMON_PORT}
  poll_interval_ms: 250
  concurrency: 4            # jobs claimed per worker pass
  lease_seconds: 60
  retention_days: ${DEFAULT_RETENTION_DAYS}        # raw-event retention (D4); compaction needs a scheduled job
  consolidate_interval_ms: ${DEFAULT_CONSOLIDATE_INTERVAL_MS}  # scheduled consolidation pass (0 disables)

security:
  network_guard: auto       # auto | enforce | off  ('off' is rejected while llm.profile is local)
  exclude_globs: []         # ADDITIONAL exclusions; .env*, *.pem, keys, credentials are always excluded
  # redaction:
  #   groups: { jwt: false }                                  # turn a built-in detector group off
  #   extra_patterns:
  #     - { id: stripe, kind: api-key, pattern: 'sk_live_[A-Za-z0-9]{24}' }
`;
}

/** The template with the project name substituted (single-quoted when YAML needs it). */
export function renderConfigForProject(projectName: string): string {
  const quoted = /^[A-Za-z0-9._@/-]+$/.test(projectName) ? projectName : JSON.stringify(projectName);
  return renderDefaultConfigYaml().replace('$PROJECT_NAME$', quoted);
}
