export {
  captureSnapshot,
  detectChanges,
  compareSnapshots,
} from './fingerprints';
export {
  createPathFilter,
  resolveRepositoryRoot,
  scanWorktree,
  type WorktreeScan,
} from './fingerprints';
export { createDriftWatcher } from './drift';
export {
  createDriftApplier,
  readCheckpointBasis,
  type AppliedCheckpoint,
  type AppliedDriftMemory,
  type AppliedRetarget,
  type CheckpointStepOutcome,
  type DriftApplier,
  type DriftApplierDeps,
  type DriftApplyResult,
  type DriftApplyStore,
  type DriftMemoryOutcome,
} from './apply-drift';
export { computeSymbolsHash, extractSymbolTable } from './symbols';
export { languageForPath, SOURCE_EXTENSIONS } from './grammar';
export {
  FileFingerprintSchema,
  FingerprintOptionsSchema,
  RepositorySnapshotSchema,
  RepositoryPathSchema,
  DetectDriftInputSchema,
  ApplyDriftInputSchema,
  ApplyDriftReportInputSchema,
  CheckpointBasisSchema,
  DriftReportSchema,
  SymbolFileSchema,
  SymbolKindSchema,
  SymbolLanguageSchema,
  SymbolOptionsSchema,
  SymbolRecordSchema,
  SymbolTableSchema,
  SkippedSymbolFileSchema,
  FingerprintError,
  type FileFingerprint,
  type RepositorySnapshot,
  type FingerprintOptions,
  type FileChange,
  type FingerprintChangeReport,
  type SkippedPath,
  type DetectDriftInput,
  type ApplyDriftInput,
  type ApplyDriftReportInput,
  type CheckpointBasis,
  type SymbolFile,
  type SymbolKind,
  type SymbolLanguage,
  type SymbolOptions,
  type SymbolRecord,
  type SymbolTable,
  type SkippedSymbolFile,
} from './schema';
