/**
 * `.cursor/rules/onememory.mdc` — the rules bootstrap (pure renderers + an idempotent patcher).
 *
 * Wire format (verified: https://cursor.com/docs/rules, fetched 2026-10-05):
 * - Project rules live in `.cursor/rules` and MUST use the `.mdc` extension; a plain `.md` file
 *   there is ignored "because it has no frontmatter to specify `description`, `globs`, and
 *   `alwaysApply`".
 * - Frontmatter keys: `description`, `globs`, `alwaysApply`. `alwaysApply: true` → the rule is
 *   included in every chat session (description/globs ignored); with `alwaysApply: false` and no
 *   `globs`/`description` the rule is included only when @-mentioned.
 * - Cursor also supports `AGENTS.md` (plain markdown, project root and subdirectories) as an
 *   alternative; the Codex adapter already writes the `AGENTS.md` pointer, so the Cursor adapter
 *   writes the Cursor-native rule instead of a second pointer into the same file.
 *
 * The rule exists to steer the agent at the MCP tools — it must be ALWAYS APPLIED (that is the
 * whole point of a bootstrap), so `alwaysApply: true` is emitted. The body is marker-fenced: a
 * re-run replaces only onememory's block and never touches the user's own frontmatter or prose.
 */

import { z } from 'zod';

import type { ScaffoldMergeResult } from './mcp-scaffold';

/** HTML comments are inert in Markdown and MDC; they fence onememory's generated block. */
export const RULES_BEGIN = '<!-- onemem:begin (generated by `onemem init` — do not edit inside this block) -->';
export const RULES_END = '<!-- onemem:end -->';

export interface CursorRuleOptions {
  /** Project name used in the heading (optional — omit for a generic block). */
  projectName?: string;
}

/** The generated rule file's frontmatter (validated, so a typo is a test failure). */
export const CursorRuleFrontmatterSchema = z.strictObject({
  description: z.string().min(1),
  alwaysApply: z.boolean(),
});
export type CursorRuleFrontmatter = z.infer<typeof CursorRuleFrontmatterSchema>;

export function buildCursorRuleFrontmatter(): CursorRuleFrontmatter {
  return CursorRuleFrontmatterSchema.parse({
    description:
      'onememory owns this project\u2019s durable memory (decisions, failures, procedures, preferences). Read and write it through the onememory MCP tools; do not hand-maintain a duplicate knowledge base.',
    alwaysApply: true,
  });
}

/** Render the YAML frontmatter block (fixed key order, quoted description, trailing newline). */
export function renderCursorRuleFrontmatter(frontmatter: CursorRuleFrontmatter = buildCursorRuleFrontmatter()): string {
  const escaped = frontmatter.description.replace(/"/g, '\\"');
  return `---\ndescription: "${escaped}"\nalwaysApply: ${String(frontmatter.alwaysApply)}\n---\n`;
}

/**
 * The marker-fenced body: states that onememory owns project memory, how to read/write it, and
 * what the hooks do. Kept short — an always-applied rule is injected into every session.
 */
export function buildOnememoryRuleBlock(options: CursorRuleOptions = {}): string {
  const heading =
    options.projectName === undefined
      ? 'Project memory (onememory)'
      : `Project memory for ${options.projectName} (onememory)`;
  return [
    RULES_BEGIN,
    `## ${heading}`,
    '',
    'Durable project memory — decisions, failures, procedures, preferences — lives in onememory,',
    'not in this rule. Do not hand-maintain a duplicate knowledge base here.',
    '',
    '- Use the `mcp__onememory__*` MCP tools (`memory_search`, `memory_get`, `memory_store`, …) to',
    '  read and write memories on demand. `memory_search` returns a cheap ID index; call',
    '  `memory_get` only for the IDs you need.',
    '- `onemem remember "<content>"` stores an explicit memory; `onemem search "<query>"` searches.',
    '- A `sessionStart` hook injects a compact, token-budgeted memory index into the conversation',
    '  (best-effort: Cursor runs `sessionStart` fire-and-forget), and the capture hooks record',
    '  commands, file edits, failures, and conversation turns for extraction.',
    RULES_END,
  ].join('\n');
}

/** The complete file for a fresh project: frontmatter + the marker-fenced block. */
export function renderCursorRule(options: CursorRuleOptions = {}): string {
  return `${renderCursorRuleFrontmatter()}${buildOnememoryRuleBlock(options)}\n`;
}

/** `true` when the document holds a complete onememory rule block (both markers, in order). */
export function hasOnememoryRuleBlock(text: string | null): boolean {
  if (text === null) return false;
  const begin = text.indexOf(RULES_BEGIN);
  return begin !== -1 && text.indexOf(RULES_END, begin) !== -1;
}

function escapeRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** `true` when the document starts with a YAML frontmatter fence. */
export function hasFrontmatter(text: string): boolean {
  return /^---\r?\n/.test(text);
}

/**
 * Merge the rule block into an existing `.cursor/rules/onememory.mdc`:
 * - absent/blank → a new document (frontmatter + block);
 * - our markers present → only the fenced block is replaced (the user's frontmatter and prose are
 *   preserved verbatim);
 * - no markers → the block is appended at the end, and the caller is told whether the existing
 *   document lacks frontmatter (Cursor would then treat the whole rule as @-mention-only).
 *
 * Never destructive: an unparseable file is impossible here (the format is markdown), and the
 * function only ever inserts or replaces its own fenced block.
 */
export function patchCursorRule(existing: string | null, options: CursorRuleOptions = {}): ScaffoldMergeResult {
  const block = buildOnememoryRuleBlock(options);
  if (existing === null || existing.trim().length === 0) {
    return { ok: true, content: renderCursorRule(options), action: 'created' };
  }
  if (hasOnememoryRuleBlock(existing)) {
    const pattern = new RegExp(`${escapeRegExp(RULES_BEGIN)}[\\s\\S]*?${escapeRegExp(RULES_END)}`);
    const content = existing.replace(pattern, block);
    return { ok: true, content, action: content === existing ? 'unchanged' : 'patched' };
  }
  const trimmed = existing.replace(/\s+$/, '');
  const content = `${trimmed.length === 0 ? '' : `${trimmed}\n\n`}${block}\n`;
  return { ok: true, content, action: content === existing ? 'unchanged' : 'patched' };
}
