/**
 * Doctor-inspection tests: every on-disk state classifies into exactly one normalized state — the
 * shape `evaluateRuntimeScaffold` (apps/api) consumes.
 */

import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { describe, expect, test } from 'bun:test';

import { hasPiPointerBlock, inspectPiMcpContent, inspectPiExtensionContent, inspectPiScaffold, piScaffoldPaths } from './scaffold-inspect';

describe('inspectPiMcpContent', () => {
  test('absent → {state: absent}', () => {
    expect(inspectPiMcpContent(null)).toMatchObject({ state: 'absent' });
  });

  test('invalid JSON → {state: invalid, detail}', () => {
    expect(inspectPiMcpContent('{ broken')).toMatchObject({ state: 'invalid' });
  });

  test('no mcpServers object → invalid', () => {
    expect(inspectPiMcpContent('{"mcpServers": []}')).toMatchObject({ state: 'invalid' });
  });

  test('no onememory entry → {state: no_entry}', () => {
    expect(inspectPiMcpContent(JSON.stringify({ mcpServers: { other: { command: 'npx' } } }))).toMatchObject({
      state: 'no_entry',
    });
  });

  test('our http entry → {state: http, url}', () => {
    expect(
      inspectPiMcpContent(JSON.stringify({ mcpServers: { onememory: { url: 'http://127.0.0.1:7331/mcp' } } })),
    ).toMatchObject({ state: 'http', url: 'http://127.0.0.1:7331/mcp' });
  });

  test('our stdio entry → {state: stdio}', () => {
    expect(
      inspectPiMcpContent(JSON.stringify({ mcpServers: { onememory: { command: 'bun', args: [] } } })),
    ).toMatchObject({ state: 'stdio' });
  });

  test('an entry with neither url nor command → unrecognized', () => {
    expect(
      inspectPiMcpContent(JSON.stringify({ mcpServers: { onememory: { enabled: false } } })),
    ).toMatchObject({ state: 'unrecognized' });
  });
});

describe('inspectPiExtensionContent', () => {
  test('absent → absent; ours → complete; foreign → no_entry with detail', () => {
    expect(inspectPiExtensionContent(null)).toMatchObject({ state: 'absent' });
    expect(inspectPiExtensionContent('/** onememory:generated (onemem init) — … */')).toMatchObject({
      state: 'complete',
    });
    expect(inspectPiExtensionContent('export default () => {};')).toMatchObject({
      state: 'no_entry',
      detail: expect.stringContaining('not generated by onemem init'),
    });
  });
});

describe('hasPiPointerBlock', () => {
  test('true only for a complete begin+end pair, in order', () => {
    const begin = '<!-- onemem:begin (generated by `onemem init` — do not edit inside this block) -->';
    const end = '<!-- onemem:end -->';
    expect(hasPiPointerBlock(null)).toBeFalse();
    expect(hasPiPointerBlock('nothing here')).toBeFalse();
    expect(hasPiPointerBlock(`${begin}\ncontent\n`)).toBeFalse(); // orphaned begin
    expect(hasPiPointerBlock(`${begin}\ncontent\n${end}\n`)).toBeTrue();
  });
});

describe('inspectPiScaffold', () => {
  test('normalizes a scaffolded project into the doctor state shape', () => {
    const root = mkdtempSync(join(tmpdir(), 'onemem-pi-inspect-'));
    try {
      const paths = piScaffoldPaths(root);
      mkdirSync(join(root, '.pi', 'extensions'), { recursive: true });
      writeFileSync(paths.mcpJson, JSON.stringify({ mcpServers: { onememory: { url: 'http://127.0.0.1:7331/mcp' } } }), 'utf8');
      writeFileSync(paths.extension, '/** onememory:generated (onemem init) */\n', 'utf8');
      writeFileSync(paths.pointer, `notes\n\n<!-- onemem:begin (generated by \`onemem init\` — do not edit inside this block) -->\nblock\n<!-- onemem:end -->\n`, 'utf8');

      const state = inspectPiScaffold(root);
      expect(state.mcp).toMatchObject({ path: paths.mcpJson, state: 'http', url: 'http://127.0.0.1:7331/mcp' });
      expect(state.hooks).toMatchObject({ path: paths.extension, state: 'complete' });
      expect(state.pointer).toMatchObject({ path: paths.pointer, present: true });
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test('an empty project reports absent everywhere', () => {
    const root = mkdtempSync(join(tmpdir(), 'onemem-pi-empty-inspect-'));
    try {
      const state = inspectPiScaffold(root);
      expect(state.mcp.state).toBe('absent');
      expect(state.hooks.state).toBe('absent');
      expect(state.pointer.present).toBeFalse();
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
