/**
 * Read-only inspection of the Pi scaffolds, for `onemem doctor` (mirrors
 * `inspectClaudeScaffold` / `inspectCodexScaffold`).
 *
 * Reports what is on disk — never judges it: the doctor compares the MCP URL against the configured
 * daemon URL and decides the status (via `evaluateRuntimeScaffold` in `@onememory/api/runtime`,
 * whose `RuntimeScaffoldState` this normalizes to). Content-level functions are pure so each state
 * is unit-tested without a filesystem.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { z } from 'zod';

import {
  MCP_SERVER_NAME,
  PI_EXTENSION_MARKER,
  PI_EXTENSION_RELPATH,
  PI_POINTER_BEGIN,
  PI_POINTER_END,
} from './scaffolds';

/** The normalized per-runtime scaffold shape the doctor's runtimes group consumes. */
export interface PiScaffoldState {
  mcp: { path: string; state: 'absent' | 'invalid' | 'no_entry' | 'http' | 'stdio' | 'unrecognized'; url?: string; detail?: string };
  hooks: { path: string; state: 'absent' | 'invalid' | 'no_entry' | 'partial' | 'complete'; missing_events?: string[]; detail?: string };
  pointer: { path: string; present: boolean };
}

/** A content-level classification: the state without the path the filesystem layer adds. */
export type PiMcpInspection = Omit<PiScaffoldState['mcp'], 'path'>;
export type PiExtensionInspection = Omit<PiScaffoldState['hooks'], 'path'>;

const ServersSchema = z.looseObject({ mcpServers: z.record(z.string(), z.unknown()).optional() });
const HttpEntrySchema = z.looseObject({ url: z.string() });
const StdioEntrySchema = z.looseObject({ command: z.string() });

function parseJson(text: string): { ok: true; value: unknown } | { ok: false; detail: string } {
  try {
    return { ok: true, value: JSON.parse(text) };
  } catch (error) {
    return { ok: false, detail: `not valid JSON (${error instanceof Error ? error.message : String(error)})` };
  }
}

/** Classify the `onememory` entry of an mcp.json document (`null` = file absent). */
export function inspectPiMcpContent(text: string | null): PiMcpInspection {
  if (text === null) return { state: 'absent' };
  const parsed = parseJson(text);
  if (!parsed.ok) return { state: 'invalid', detail: parsed.detail };
  const document = ServersSchema.safeParse(parsed.value);
  if (!document.success || typeof parsed.value !== 'object' || parsed.value === null || Array.isArray(parsed.value)) {
    return { state: 'invalid', detail: 'not a JSON object with an object-valued "mcpServers"' };
  }
  const entry = document.data.mcpServers?.[MCP_SERVER_NAME];
  if (entry === undefined) return { state: 'no_entry' };
  const http = HttpEntrySchema.safeParse(entry);
  if (http.success) return { state: 'http', url: http.data.url };
  if (StdioEntrySchema.safeParse(entry).success) return { state: 'stdio' };
  return { state: 'unrecognized', detail: 'the onememory entry has neither a url (streamable HTTP) nor a command (stdio)' };
}

/** Whether the extension shim is ours: the generated marker in the file (`null` = absent). */
export function inspectPiExtensionContent(text: string | null): PiExtensionInspection {
  if (text === null) return { state: 'absent' };
  if (text.includes(PI_EXTENSION_MARKER)) return { state: 'complete' };
  return {
    state: 'no_entry',
    detail: 'the extension file exists but was not generated by onemem init',
  };
}

/** `true` when the document holds a complete onememory pointer block. */
export function hasPiPointerBlock(text: string | null): boolean {
  if (text === null) return false;
  const begin = text.indexOf(PI_POINTER_BEGIN);
  return begin !== -1 && text.indexOf(PI_POINTER_END, begin) !== -1;
}

/** The scaffold paths `onemem init --with-pi` writes (project scope under `root`). */
export function piScaffoldPaths(root: string, scope: 'project' | 'user' = 'project'): { mcpJson: string; extension: string; pointer: string } {
  const base = scope === 'project' ? join(root, '.pi') : root;
  return {
    mcpJson: join(base, 'mcp.json'),
    extension: join(base, PI_EXTENSION_RELPATH),
    pointer: join(base, 'APPEND_SYSTEM.md'),
  };
}

/** Inspect the Pi scaffolds under `root` (project scope reads `<root>/.pi/`). */
export function inspectPiScaffold(root: string, scope: 'project' | 'user' = 'project'): PiScaffoldState {
  const paths = piScaffoldPaths(root, scope);
  return {
    mcp: { path: paths.mcpJson, ...inspectPiMcpContent(readIfExists(paths.mcpJson)) },
    hooks: { path: paths.extension, ...inspectPiExtensionContent(readIfExists(paths.extension)) },
    pointer: { path: paths.pointer, present: hasPiPointerBlock(readIfExists(paths.pointer)) },
  };
}

function readIfExists(path: string): string | null {
  return existsSync(path) ? readFileSync(path, 'utf8') : null;
}
