/**
 * `scaffoldPi` — the one function `onemem init` calls to wire Pi (the init-wiring seam, mirroring
 * `scaffoldCodex`).
 *
 * What it writes (project scope, from the project root — user scope writes the same three
 * artifacts under the Pi agent dir, default `~/.pi/agent`):
 *   `.pi/mcp.json`               — the `mcpServers.onememory` entry (idempotent merge)
 *   `.pi/extensions/onememory.ts` — the capture + injection extension shim (ours alone: replaced
 *                                  when the generated marker is present, skipped when it is not)
 *   `.pi/APPEND_SYSTEM.md`       — the compact generated pointer block (marker-fenced, idempotent)
 *
 * The MCP entry is the daemon-backed Streamable HTTP form when `transport: 'http'` + `url` are
 * passed (what `onemem init` does, ADR-0010 amendment 2026-10-04), else the stdio form. An invalid
 * http `url` throws BEFORE any file is touched; every other problem is reported through
 * `warnings` / `skipped` — never by overwriting a file the user owns.
 *
 * The function is deliberately filesystem-thin: all content decisions live in the pure renderers
 * (`scaffolds.ts`), so `dryRun` returns the exact bytes without touching disk, and every artifact
 * is unit-tested on its own.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import {
  buildPiExtensionFile,
  buildPiPointerBlock,
  mergePiMcpJson,
  mergePiPointerBlock,
  PI_EXTENSION_MARKER,
  PI_EXTENSION_RELPATH,
  PI_POINTER_BEGIN,
  PI_POINTER_END,
  type PiMcpOptions,
} from './scaffolds';

export type PiScaffoldScope = 'project' | 'user';

export interface ScaffoldPiOptions extends PiMcpOptions {
  /** `project` writes into `<root>/.pi/`; `user` writes into the Pi agent dir (`<root>` = the dir itself). */
  scope: PiScaffoldScope;
  /** Project root (project scope) or Pi agent directory (user scope). */
  root: string;
  /** Project name for the pointer heading (optional). */
  projectName?: string;
  /** Compute the artifacts and return them without writing (default false). */
  dryRun?: boolean;
}

export interface ScaffoldedFile {
  /** Absolute path (or the would-be path in dry-run). */
  path: string;
  action: 'created' | 'patched' | 'unchanged' | 'skipped';
  /** The exact bytes written (or that would be written); the existing bytes when skipped. */
  content: string;
}

export interface ScaffoldPiResult {
  files: ScaffoldedFile[];
  /** Operator-facing notes (project trust, reload, unparseable files, …). */
  warnings: string[];
}

export function scaffoldPi(options: ScaffoldPiOptions): ScaffoldPiResult {
  const warnings: string[] = [];
  const files: ScaffoldedFile[] = [];

  const base = options.scope === 'project' ? join(options.root, '.pi') : options.root;
  const paths = {
    mcpJson: join(base, 'mcp.json'),
    extension: join(base, PI_EXTENSION_RELPATH),
    pointer: join(base, 'APPEND_SYSTEM.md'),
  };

  // --- mcp.json (the MCP server) ------------------------------------------------
  const mcp = mergePiMcpJson(readIfExists(paths.mcpJson), options);
  if (mcp.ok) {
    files.push({
      path: paths.mcpJson,
      action: mcp.action,
      content: mcp.content,
    });
  } else {
    files.push({ path: paths.mcpJson, action: 'skipped', content: readIfExists(paths.mcpJson) ?? '' });
    warnings.push(mcp.error);
  }
  if (options.scope === 'project') {
    warnings.push(
      'Pi reads project .pi/mcp.json and .pi/extensions only after project trust is granted — accept the trust prompt the first time you open this project in Pi',
    );
  }

  // --- the extension shim (ours alone) --------------------------------------------
  const generated = buildPiExtensionFile();
  const existingExtension = readIfExists(paths.extension);
  if (existingExtension === null) {
    files.push({ path: paths.extension, action: 'created', content: generated });
  } else if (existingExtension.includes(PI_EXTENSION_MARKER)) {
    files.push({
      path: paths.extension,
      action: existingExtension === generated ? 'unchanged' : 'patched',
      content: generated,
    });
  } else {
    files.push({ path: paths.extension, action: 'skipped', content: existingExtension });
    warnings.push(
      `${PI_EXTENSION_RELPATH} exists but was not generated by onemem init (no "${PI_EXTENSION_MARKER}" marker) and was left untouched — rename it if you want onememory's extension there`,
    );
  }
  warnings.push(
    'run /reload (or restart Pi) after scaffolding outside a session — extensions and mcp.json load at session start',
  );

  // --- APPEND_SYSTEM.md (the pointer) ----------------------------------------------
  const block = buildPiPointerBlock({
    ...(options.projectName === undefined ? {} : { projectName: options.projectName }),
  });
  const existingPointer = readIfExists(paths.pointer);
  if (
    existingPointer !== null &&
    existingPointer.includes(PI_POINTER_BEGIN) &&
    !existingPointer.includes(PI_POINTER_END)
  ) {
    files.push({ path: paths.pointer, action: 'skipped', content: existingPointer });
    warnings.push(
      'APPEND_SYSTEM.md has an orphaned onememory begin marker (no end marker) and was left untouched — remove the stray marker and re-run onemem init',
    );
  } else {
    const merged = mergePiPointerBlock(existingPointer ?? '', block);
    files.push({
      path: paths.pointer,
      action: existingPointer === null ? 'created' : merged === existingPointer ? 'unchanged' : 'patched',
      content: merged,
    });
  }

  if (options.dryRun !== true) {
    for (const file of files) {
      if (file.action === 'skipped' || file.action === 'unchanged') continue;
      mkdirSync(dirname(file.path), { recursive: true });
      writeFileSync(file.path, file.content, 'utf8');
    }
  }
  return { files, warnings };
}

function readIfExists(path: string): string | null {
  if (!existsSync(path)) return null;
  return readFileSync(path, 'utf8');
}
