/**
 * Read-only inspection of the project-scope OpenCode scaffolds, for `onemem doctor` (mirrors
 * `inspectPiScaffold` / `inspectCursorScaffold`).
 *
 * Reports what is on disk — never judges it: the doctor compares the MCP URL against the
 * configured daemon URL and decides the status (via `evaluateRuntimeScaffold` in
 * `@onememory-ai/api/runtime`, whose `RuntimeScaffoldState` this normalizes to). Content-level
 * functions are pure so each state is unit-tested without a filesystem.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { z } from 'zod';

import { MCP_SERVER_NAME } from './wire';
import { openCodeScaffoldPaths } from './scaffold';
import {
  OPENCODE_INSTRUCTIONS_ENTRY,
  OPENCODE_PLUGIN_MARKER,
  OPENCODE_POINTER_BEGIN,
  OPENCODE_POINTER_END,
} from './scaffolds';

/** The normalized per-runtime scaffold shape the doctor's runtimes group consumes. */
export interface OpenCodeScaffoldState {
  mcp: { path: string; state: 'absent' | 'invalid' | 'no_entry' | 'http' | 'stdio' | 'unrecognized'; url?: string; detail?: string };
  hooks: { path: string; state: 'absent' | 'invalid' | 'no_entry' | 'partial' | 'complete'; missing_events?: string[]; detail?: string };
  pointer: { path: string; present: boolean };
}

/** A content-level classification: the state without the path the filesystem layer adds. */
export type OpenCodeConfigInspection = Omit<OpenCodeScaffoldState['mcp'], 'path'>;
export type OpenCodePluginInspection = Omit<OpenCodeScaffoldState['hooks'], 'path'>;

const ConfigShapeSchema = z.looseObject({
  mcp: z.record(z.string(), z.unknown()).optional(),
  instructions: z.array(z.string()).optional(),
});
const HttpEntrySchema = z.looseObject({ type: z.literal('remote'), url: z.string() });
const StdioEntrySchema = z.looseObject({ type: z.literal('local'), command: z.array(z.string()) });

function parseJson(text: string): { ok: true; value: unknown } | { ok: false; detail: string } {
  try {
    return { ok: true, value: JSON.parse(text) };
  } catch (error) {
    return { ok: false, detail: `not valid JSON (${error instanceof Error ? error.message : String(error)})` };
  }
}

/** Classify the `mcp.onememory` entry of an `opencode.json` document (`null` = file absent). */
export function inspectOpenCodeConfigContent(text: string | null): OpenCodeConfigInspection {
  if (text === null) return { state: 'absent' };
  const parsed = parseJson(text);
  if (!parsed.ok) return { state: 'invalid', detail: parsed.detail };
  const document = ConfigShapeSchema.safeParse(parsed.value);
  if (
    !document.success ||
    typeof parsed.value !== 'object' ||
    parsed.value === null ||
    Array.isArray(parsed.value)
  ) {
    return { state: 'invalid', detail: 'not a JSON object with an object-valued "mcp"' };
  }
  const entry = document.data.mcp?.[MCP_SERVER_NAME];
  if (entry === undefined) return { state: 'no_entry' };
  const http = HttpEntrySchema.safeParse(entry);
  if (http.success) return { state: 'http', url: http.data.url };
  if (StdioEntrySchema.safeParse(entry).success) return { state: 'stdio' };
  return {
    state: 'unrecognized',
    detail: 'the onememory entry is neither a remote (type: "remote", url) nor a local (type: "local", command) server',
  };
}

/** Whether the plugin shim is ours: the generated marker in the file (`null` = absent). */
export function inspectOpenCodePluginContent(text: string | null): OpenCodePluginInspection {
  if (text === null) return { state: 'absent' };
  if (text.includes(OPENCODE_PLUGIN_MARKER)) return { state: 'complete' };
  return {
    state: 'no_entry',
    detail: 'the plugin file exists but was not generated by onemem init',
  };
}

/** The scaffold paths `onemem init --with-opencode` writes (project scope under `root`). */
export function openCodeInspectPaths(root: string): { configJson: string; plugin: string; pointer: string } {
  return openCodeScaffoldPaths(root);
}

/** Inspect the project-scope OpenCode scaffolds under `root`. */
export function inspectOpenCodeScaffold(root: string): OpenCodeScaffoldState {
  const paths = openCodeScaffoldPaths(root);
  const pointerPath = join(root, OPENCODE_INSTRUCTIONS_ENTRY);
  return {
    mcp: { path: paths.configJson, ...inspectOpenCodeConfigContent(readIfExists(paths.configJson)) },
    hooks: { path: paths.plugin, ...inspectOpenCodePluginContent(readIfExists(paths.plugin)) },
    pointer: {
      path: pointerPath,
      present: hasOpenCodePointerBlockContent(readIfExists(pointerPath)),
    },
  };
}

/** `true` when the instructions file holds a complete onememory pointer block. */
export function hasOpenCodePointerBlockContent(text: string | null): boolean {
  if (text === null) return false;
  const begin = text.indexOf(OPENCODE_POINTER_BEGIN);
  return begin !== -1 && text.indexOf(OPENCODE_POINTER_END, begin) !== -1;
}

function readIfExists(path: string): string | null {
  return existsSync(path) ? readFileSync(path, 'utf8') : null;
}
