/**
 * `scaffoldOpenCode` — the one function `onemem init` calls to wire OpenCode (the init-wiring
 * seam, mirroring `scaffoldPi` / `scaffoldCursor` / `scaffoldCodex`).
 *
 * What it writes (project scope, from the project root):
 *   `opencode.json`                  — the `mcp.onememory` entry + the `instructions` entry
 *                                     (idempotent merge; a file we cannot parse is never touched)
 *   `.opencode/plugins/onememory.ts` — the capture + injection plugin shim (ours alone: replaced
 *                                     when the generated marker is present, skipped when not —
 *                                     local plugin files auto-load, no config entry needed)
 *   `.opencode/onememory.md`         — the compact generated pointer block (marker-fenced,
 *                                     idempotent), registered via the `instructions` entry
 *
 * The MCP entry is the daemon-backed Streamable HTTP form when `transport: 'http'` + `url` are
 * passed (what `onemem init` does, ADR-0010 amendment 2026-10-04), else the stdio form. An
 * invalid http `url` throws BEFORE any file is touched; every other problem is reported through
 * `warnings` / `skipped` — never by overwriting a file the user owns.
 *
 * The function is deliberately filesystem-thin: all content decisions live in the pure renderers
 * (`scaffolds.ts`), so `dryRun` returns the exact bytes without touching disk, and every artifact
 * is unit-tested on its own.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import {
  buildOpenCodePluginFile,
  buildOpenCodePointerBlock,
  mergeOpenCodeConfigJson,
  mergeOpenCodePointerBlock,
  OPENCODE_INSTRUCTIONS_ENTRY,
  OPENCODE_PLUGIN_MARKER,
  OPENCODE_PLUGIN_RELPATH,
  OPENCODE_POINTER_BEGIN,
  OPENCODE_POINTER_END,
  type OpenCodeMcpOptions,
} from './scaffolds';

export interface ScaffoldOpenCodeOptions extends OpenCodeMcpOptions {
  /** Project root — the directory that contains (or will contain) `opencode.json` and `.opencode/`. */
  root: string;
  /** Project name for the pointer heading (optional). */
  projectName?: string;
  /** Compute the artifacts and return them without writing (default false). */
  dryRun?: boolean;
}

export interface ScaffoldedFile {
  /** Absolute path (or the would-be path in dry-run). */
  path: string;
  action: 'created' | 'patched' | 'unchanged' | 'skipped';
  /** The exact bytes written (or that would be written); the existing bytes when skipped. */
  content: string;
}

export interface ScaffoldOpenCodeResult {
  files: ScaffoldedFile[];
  /** Operator-facing notes (review steps, unparseable files, reload, …). */
  warnings: string[];
}

/** The project-scope artifact paths `onemem init --with-opencode` writes. */
export function openCodeScaffoldPaths(root: string): { configJson: string; plugin: string; pointer: string } {
  return {
    configJson: join(root, 'opencode.json'),
    plugin: join(root, '.opencode', OPENCODE_PLUGIN_RELPATH),
    pointer: join(root, OPENCODE_INSTRUCTIONS_ENTRY),
  };
}

export function scaffoldOpenCode(options: ScaffoldOpenCodeOptions): ScaffoldOpenCodeResult {
  const warnings: string[] = [];
  const files: ScaffoldedFile[] = [];
  const paths = openCodeScaffoldPaths(options.root);

  // --- opencode.json (the MCP server + the instructions registration) -----------------
  const existingConfig = readIfExists(paths.configJson);
  const config = mergeOpenCodeConfigJson(existingConfig, options);
  if (!config.ok) {
    warnings.push(config.error);
    files.push({ path: paths.configJson, action: 'skipped', content: existingConfig ?? '' });
  } else {
    files.push({
      path: paths.configJson,
      action: existingConfig === null ? 'created' : config.action,
      content: config.content,
    });
  }

  // --- the plugin shim (ours alone) ----------------------------------------------------
  const generatedPlugin = buildOpenCodePluginFile();
  const existingPlugin = readIfExists(paths.plugin);
  if (existingPlugin === null) {
    files.push({ path: paths.plugin, action: 'created', content: generatedPlugin });
  } else if (existingPlugin.includes(OPENCODE_PLUGIN_MARKER)) {
    files.push({
      path: paths.plugin,
      action: existingPlugin === generatedPlugin ? 'unchanged' : 'patched',
      content: generatedPlugin,
    });
  } else {
    files.push({ path: paths.plugin, action: 'skipped', content: existingPlugin });
    warnings.push(
      `${OPENCODE_PLUGIN_RELPATH} exists but was not generated by onemem init (no "${OPENCODE_PLUGIN_MARKER}" marker) and was left untouched — rename it if you want onememory's plugin there`,
    );
  }

  // --- .opencode/onememory.md (the pointer) ---------------------------------------------
  const block = buildOpenCodePointerBlock({
    ...(options.projectName === undefined ? {} : { projectName: options.projectName }),
  });
  const existingPointer = readIfExists(paths.pointer);
  if (
    existingPointer !== null &&
    existingPointer.includes(OPENCODE_POINTER_BEGIN) &&
    !existingPointer.includes(OPENCODE_POINTER_END)
  ) {
    files.push({ path: paths.pointer, action: 'skipped', content: existingPointer });
    warnings.push(
      '.opencode/onememory.md has an orphaned onememory begin marker (no end marker) and was left untouched — remove the stray marker and re-run onemem init',
    );
  } else {
    const merged = mergeOpenCodePointerBlock(existingPointer ?? '', block);
    files.push({
      path: paths.pointer,
      action: existingPointer === null ? 'created' : merged === existingPointer ? 'unchanged' : 'patched',
      content: merged,
    });
  }

  warnings.push(
    'OpenCode loads plugins and config at startup — restart opencode after scaffolding outside a session (files in .opencode/plugins/ are picked up on the next launch)',
  );
  warnings.push(
    'OpenCode asks before running MCP tools by default — allow the onememory tools (or configure the permission for the onememory server) so the agent can read and write memory unattended',
  );

  if (options.dryRun !== true) {
    for (const file of files) {
      if (file.action === 'skipped' || file.action === 'unchanged') continue;
      mkdirSync(dirname(file.path), { recursive: true });
      writeFileSync(file.path, file.content, 'utf8');
    }
  }
  return { files, warnings };
}

/** Dry-run helper: the exact bytes `scaffoldOpenCode` would write (no filesystem access at all). */
export function renderOpenCodeScaffold(options: Omit<ScaffoldOpenCodeOptions, 'root' | 'dryRun'> = {}): ScaffoldOpenCodeResult {
  const config = mergeOpenCodeConfigJson(null, options);
  if (!config.ok) {
    // mergeOpenCodeConfigJson only fails on an EXISTING unparseable file; with `null` it cannot.
    throw new Error(`renderOpenCodeScaffold: config merge failed unexpectedly: ${config.error}`);
  }
  return {
    files: [
      { path: 'opencode.json', action: 'created', content: config.content },
      { path: `.opencode/${OPENCODE_PLUGIN_RELPATH}`, action: 'created', content: buildOpenCodePluginFile() },
      { path: OPENCODE_INSTRUCTIONS_ENTRY, action: 'created', content: `${buildOpenCodePointerBlock(options)}\n` },
    ],
    warnings: [],
  };
}

function readIfExists(path: string): string | null {
  if (!existsSync(path)) return null;
  return readFileSync(path, 'utf8');
}
